/**
 * Frontend-only mock catalog for Market Research stages 1–3.
 * Feels like a live store scan; no CMS/API calls yet.
 */

export type ScopeMatch = "Exact" | "Close" | "Broader" | "Ambiguous";

export type VariationType =
  | "Primary term"
  | "Common synonym"
  | "Alternative wording"
  | "Phrase variation"
  | "Spelling variation"
  | "Regional terminology"
  | "Broader market term"
  | "Singular variation"
  | "Audience variation";

export type MockCollection = {
  id: string;
  name: string;
  productCount: number;
  /** Storefront description the Stage 3 agent reads (when the store has one). */
  description?: string;
  /** Public PLP path on the client's site. */
  plpPath?: string;
  lastSyncedLabel?: string;
  /** "All X" collections that already contain every product of the niche. */
  coversNiche?: boolean;
};

export type MockNiche = {
  id: string;
  name: string;
  productCount: number;
  collections: MockCollection[];
};

export type MockSeedRow = {
  id: string;
  /** Matches MockCollection.id for Stage 2 → Stage 3 filtering. */
  collectionId: string;
  broadSeedVariation: string;
  canonicalNicheSeed: string;
  selectedCollection: string;
  broadParentNiche: string;
  productCount: number;
  variationType: VariationType;
  scopeMatch: ScopeMatch;
  /** Added by the customer, not generated by the agent. */
  manual?: boolean;
};

export type MarketResearchStage = 1 | 2 | 3;

export type MarketResearchProject = {
  id: string;
  name: string;
  status: "active" | "completed";
  storeLabel: string;
  /** Mock: which collections look "selected" in stage 2 (display only). */
  highlightedCollectionIds: string[];
};

export const MAX_MARKET_RESEARCH_PROJECTS = 3;

export const MOCK_NICHES: MockNiche[] = [
  {
    id: "eyewear",
    name: "Eyewear",
    productCount: 6850,
    collections: [
      {
        id: "sunglasses",
        name: "Sunglasses",
        productCount: 4200,
        description:
          "All sunglasses across men's, women's and unisex frames, every lens type.",
        plpPath: "/collections/sunglasses",
        lastSyncedLabel: "Synced 2 hours ago",
      },
      {
        id: "womens-sunglasses",
        name: "Women's Sunglasses",
        productCount: 2100,
        description: "Sunglasses merchandised for women.",
        plpPath: "/collections/womens-sunglasses",
        lastSyncedLabel: "Synced 2 hours ago",
      },
      {
        id: "eyeglasses",
        name: "Eyeglasses",
        productCount: 1650,
        description: "Prescription-ready optical frames.",
        plpPath: "/collections/eyeglasses",
        lastSyncedLabel: "Synced yesterday",
      },
      {
        id: "eyewear-accessories",
        name: "Accessories",
        productCount: 300,
        description: "Cases, cloths, cords and lens care.",
        plpPath: "/collections/eyewear-accessories",
        lastSyncedLabel: "Synced yesterday",
      },
    ],
  },
  {
    id: "toys",
    name: "Toys",
    productCount: 3016,
    collections: [
      {
        id: "all-toys",
        name: "All Toys",
        productCount: 3016,
        description: "Every toy on the store, all ages and categories.",
        plpPath: "/collections/all-toys",
        lastSyncedLabel: "Synced 2 hours ago",
        coversNiche: true,
      },
      {
        id: "educational-toys",
        name: "Educational Toys",
        productCount: 419,
        description: "Learning and development toys for ages 2–10.",
        plpPath: "/collections/educational-toys",
        lastSyncedLabel: "Synced 2 hours ago",
      },
      {
        id: "activity-toys",
        name: "Activity Toys",
        productCount: 134,
        description: "Outdoor and movement play.",
        plpPath: "/collections/activity-toys",
        lastSyncedLabel: "Synced 3 days ago",
      },
      {
        id: "board-games",
        name: "Board Games",
        productCount: 421,
        description: "Family and strategy tabletop games.",
        plpPath: "/collections/board-games",
        lastSyncedLabel: "Synced 2 hours ago",
      },
      {
        id: "rc-toys",
        name: "Remote-Controlled Toys",
        productCount: 36,
        description: "RC cars, drones and boats.",
        plpPath: "/collections/rc-toys",
        lastSyncedLabel: "Synced 3 days ago",
      },
    ],
  },
  {
    id: "watches",
    name: "Watches",
    productCount: 980,
    collections: [
      {
        id: "all-watches",
        name: "All Watches",
        productCount: 980,
        description: "Every watch on the store.",
        plpPath: "/collections/all-watches",
        lastSyncedLabel: "Synced yesterday",
        coversNiche: true,
      },
      {
        id: "smartwatches",
        name: "Smartwatches",
        productCount: 240,
        description: "Connected and fitness watches.",
        plpPath: "/collections/smartwatches",
        lastSyncedLabel: "Synced yesterday",
      },
      {
        id: "classic-watches",
        name: "Classic Watches",
        productCount: 520,
        description: "Analog dress and casual watches.",
        plpPath: "/collections/classic-watches",
        lastSyncedLabel: "Synced yesterday",
      },
    ],
  },
];

/** Stage 3 sample bank — plan examples (Sunglasses / Women's Sunglasses / Toys). */
export const MOCK_SEED_ROWS: MockSeedRow[] = [
  {
    id: "s1",
    collectionId: "sunglasses",
    broadSeedVariation: "Sunglasses",
    canonicalNicheSeed: "Sunglasses",
    selectedCollection: "Sunglasses",
    broadParentNiche: "Eyewear",
    productCount: 4200,
    variationType: "Primary term",
    scopeMatch: "Exact",
  },
  {
    id: "s2",
    collectionId: "sunglasses",
    broadSeedVariation: "Sun glasses",
    canonicalNicheSeed: "Sunglasses",
    selectedCollection: "Sunglasses",
    broadParentNiche: "Eyewear",
    productCount: 4200,
    variationType: "Spelling variation",
    scopeMatch: "Exact",
  },
  {
    id: "s3",
    collectionId: "sunglasses",
    broadSeedVariation: "Shades",
    canonicalNicheSeed: "Sunglasses",
    selectedCollection: "Sunglasses",
    broadParentNiche: "Eyewear",
    productCount: 4200,
    variationType: "Common synonym",
    scopeMatch: "Close",
  },
  {
    id: "s4",
    collectionId: "sunglasses",
    broadSeedVariation: "Eyewear",
    canonicalNicheSeed: "Sunglasses",
    selectedCollection: "Sunglasses",
    broadParentNiche: "Eyewear",
    productCount: 4200,
    variationType: "Broader market term",
    scopeMatch: "Broader",
  },
  {
    id: "s5",
    collectionId: "sunglasses",
    broadSeedVariation: "Glasses",
    canonicalNicheSeed: "Sunglasses",
    selectedCollection: "Sunglasses",
    broadParentNiche: "Eyewear",
    productCount: 4200,
    variationType: "Alternative wording",
    scopeMatch: "Ambiguous",
  },
  {
    id: "s6",
    collectionId: "womens-sunglasses",
    broadSeedVariation: "Women’s sunglasses",
    canonicalNicheSeed: "Women’s Sunglasses",
    selectedCollection: "Women's Sunglasses",
    broadParentNiche: "Eyewear",
    productCount: 2100,
    variationType: "Primary term",
    scopeMatch: "Exact",
  },
  {
    id: "s7",
    collectionId: "womens-sunglasses",
    broadSeedVariation: "Sunglasses for women",
    canonicalNicheSeed: "Women’s Sunglasses",
    selectedCollection: "Women's Sunglasses",
    broadParentNiche: "Eyewear",
    productCount: 2100,
    variationType: "Phrase variation",
    scopeMatch: "Exact",
  },
  {
    id: "s8",
    collectionId: "womens-sunglasses",
    broadSeedVariation: "Ladies’ sunglasses",
    canonicalNicheSeed: "Women’s Sunglasses",
    selectedCollection: "Women's Sunglasses",
    broadParentNiche: "Eyewear",
    productCount: 2100,
    variationType: "Common synonym",
    scopeMatch: "Exact",
  },
  {
    id: "s9",
    collectionId: "womens-sunglasses",
    broadSeedVariation: "Women’s eyewear",
    canonicalNicheSeed: "Women’s Sunglasses",
    selectedCollection: "Women's Sunglasses",
    broadParentNiche: "Eyewear",
    productCount: 2100,
    variationType: "Broader market term",
    scopeMatch: "Broader",
  },
  {
    id: "s10",
    collectionId: "womens-sunglasses",
    broadSeedVariation: "Women’s glasses",
    canonicalNicheSeed: "Women’s Sunglasses",
    selectedCollection: "Women's Sunglasses",
    broadParentNiche: "Eyewear",
    productCount: 2100,
    variationType: "Alternative wording",
    scopeMatch: "Ambiguous",
  },
  // Toys — plan Example 2
  {
    id: "t1",
    collectionId: "all-toys",
    broadSeedVariation: "Toys",
    canonicalNicheSeed: "Toys",
    selectedCollection: "All Toys",
    broadParentNiche: "Toys",
    productCount: 3016,
    variationType: "Primary term",
    scopeMatch: "Exact",
  },
  {
    id: "t2",
    collectionId: "all-toys",
    broadSeedVariation: "Toy",
    canonicalNicheSeed: "Toys",
    selectedCollection: "All Toys",
    broadParentNiche: "Toys",
    productCount: 3016,
    variationType: "Singular variation",
    scopeMatch: "Close",
  },
  {
    id: "t3",
    collectionId: "all-toys",
    broadSeedVariation: "Playthings",
    canonicalNicheSeed: "Toys",
    selectedCollection: "All Toys",
    broadParentNiche: "Toys",
    productCount: 3016,
    variationType: "Common synonym",
    scopeMatch: "Close",
  },
  {
    id: "t4",
    collectionId: "all-toys",
    broadSeedVariation: "Kids’ products",
    canonicalNicheSeed: "Toys",
    selectedCollection: "All Toys",
    broadParentNiche: "Toys",
    productCount: 3016,
    variationType: "Broader market term",
    scopeMatch: "Broader",
  },
  {
    id: "t5",
    collectionId: "all-toys",
    broadSeedVariation: "Children’s toys",
    canonicalNicheSeed: "Toys",
    selectedCollection: "All Toys",
    broadParentNiche: "Toys",
    productCount: 3016,
    variationType: "Audience variation",
    scopeMatch: "Close",
  },
  {
    id: "t6",
    collectionId: "educational-toys",
    broadSeedVariation: "Educational toys",
    canonicalNicheSeed: "Educational Toys",
    selectedCollection: "Educational Toys",
    broadParentNiche: "Toys",
    productCount: 419,
    variationType: "Primary term",
    scopeMatch: "Exact",
  },
  {
    id: "t7",
    collectionId: "educational-toys",
    broadSeedVariation: "Learning toys",
    canonicalNicheSeed: "Educational Toys",
    selectedCollection: "Educational Toys",
    broadParentNiche: "Toys",
    productCount: 419,
    variationType: "Common synonym",
    scopeMatch: "Close",
  },
  {
    id: "t8",
    collectionId: "educational-toys",
    broadSeedVariation: "Learning products for kids",
    canonicalNicheSeed: "Educational Toys",
    selectedCollection: "Educational Toys",
    broadParentNiche: "Toys",
    productCount: 419,
    variationType: "Alternative wording",
    scopeMatch: "Broader",
  },
  {
    id: "t9",
    collectionId: "educational-toys",
    broadSeedVariation: "Educational play products",
    canonicalNicheSeed: "Educational Toys",
    selectedCollection: "Educational Toys",
    broadParentNiche: "Toys",
    productCount: 419,
    variationType: "Alternative wording",
    scopeMatch: "Close",
  },
  {
    id: "t10",
    collectionId: "board-games",
    broadSeedVariation: "Board games",
    canonicalNicheSeed: "Board Games",
    selectedCollection: "Board Games",
    broadParentNiche: "Toys",
    productCount: 421,
    variationType: "Primary term",
    scopeMatch: "Exact",
  },
  {
    id: "t11",
    collectionId: "board-games",
    broadSeedVariation: "Tabletop games",
    canonicalNicheSeed: "Board Games",
    selectedCollection: "Board Games",
    broadParentNiche: "Toys",
    productCount: 421,
    variationType: "Common synonym",
    scopeMatch: "Close",
  },
  {
    id: "t12",
    collectionId: "board-games",
    broadSeedVariation: "Table games",
    canonicalNicheSeed: "Board Games",
    selectedCollection: "Board Games",
    broadParentNiche: "Toys",
    productCount: 421,
    variationType: "Alternative wording",
    scopeMatch: "Ambiguous",
  },
  {
    id: "t13",
    collectionId: "board-games",
    broadSeedVariation: "Board game",
    canonicalNicheSeed: "Board Games",
    selectedCollection: "Board Games",
    broadParentNiche: "Toys",
    productCount: 421,
    variationType: "Singular variation",
    scopeMatch: "Exact",
  },
];

/** Build Stage 3 rows only for Stage 2 selections (plan: one family per collection). */
export function getSeedRowsForCollections(
  collectionIds: string[]
): MockSeedRow[] {
  const selected = new Set(collectionIds);
  const curated = MOCK_SEED_ROWS.filter((r) => selected.has(r.collectionId));
  const covered = new Set(curated.map((r) => r.collectionId));

  const synthesized: MockSeedRow[] = [];
  for (const niche of MOCK_NICHES) {
    for (const collection of niche.collections) {
      if (!selected.has(collection.id) || covered.has(collection.id)) continue;
      synthesized.push(
        {
          id: `gen-${collection.id}-primary`,
          collectionId: collection.id,
          broadSeedVariation: collection.name,
          canonicalNicheSeed: collection.name,
          selectedCollection: collection.name,
          broadParentNiche: niche.name,
          productCount: collection.productCount,
          variationType: "Primary term",
          scopeMatch: "Exact",
        },
        {
          id: `gen-${collection.id}-broader`,
          collectionId: collection.id,
          broadSeedVariation: niche.name,
          canonicalNicheSeed: collection.name,
          selectedCollection: collection.name,
          broadParentNiche: niche.name,
          productCount: collection.productCount,
          variationType: "Broader market term",
          scopeMatch: "Broader",
        }
      );
    }
  }

  return [...curated, ...synthesized];
}

export type SeedSeedGroup = {
  canonicalNicheSeed: string;
  selectedCollection: string;
  broadParentNiche: string;
  productCount: number;
  rows: MockSeedRow[];
};

/** Plan: results are compared grouped by Canonical Niche Seed. */
export function groupSeedRowsByCanonical(rows: MockSeedRow[]): SeedSeedGroup[] {
  const groups = new Map<string, SeedSeedGroup>();
  for (const row of rows) {
    const key = `${row.collectionId}::${row.canonicalNicheSeed}`;
    const existing = groups.get(key);
    if (existing) {
      existing.rows.push(row);
      continue;
    }
    groups.set(key, {
      canonicalNicheSeed: row.canonicalNicheSeed,
      selectedCollection: row.selectedCollection,
      broadParentNiche: row.broadParentNiche,
      productCount: row.productCount,
      rows: [row],
    });
  }
  return Array.from(groups.values());
}

/** Terms the plan explicitly keeps out of Stage 3. */
export const STAGE3_EXCLUDED_EXAMPLES: string[] = [
  "Styles — aviator sunglasses, polarized sunglasses",
  "Features and materials — wooden educational toys",
  "Brands and models",
  "Use cases and audiences — toys for three-year-olds",
  "Long-tail combinations — family board games, STEM toys",
];

export function seedRowsToCsv(rows: MockSeedRow[]): string {
  const header = [
    "Broad Seed Variation",
    "Canonical Niche Seed",
    "Selected Collection",
    "Broad Parent Niche",
    "Product Count",
    "Variation Type",
    "Scope Match",
  ];
  const escape = (value: string | number) => {
    const text = String(value);
    return /[",\n]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text;
  };
  const lines = rows.map((row) =>
    [
      row.broadSeedVariation,
      row.canonicalNicheSeed,
      row.selectedCollection,
      row.broadParentNiche,
      row.productCount,
      row.variationType,
      row.scopeMatch,
    ]
      .map(escape)
      .join(",")
  );
  return [header.join(","), ...lines].join("\n");
}

/**
 * Unique products behind a Stage 2 selection. An "All X" collection already
 * contains its siblings, so summing parent + children would double count.
 */
export function countProductsForCollections(collectionIds: string[]): number {
  const selected = new Set(collectionIds);
  let total = 0;
  for (const niche of MOCK_NICHES) {
    const picked = niche.collections.filter((c) => selected.has(c.id));
    if (picked.length === 0) continue;
    if (picked.some((c) => c.coversNiche)) {
      total += niche.productCount;
      continue;
    }
    const summed = picked.reduce((sum, c) => sum + c.productCount, 0);
    total += Math.min(summed, niche.productCount);
  }
  return total;
}

/** Raw sum before dedupe — used to explain the difference to the customer. */
export function sumProductsForCollections(collectionIds: string[]): number {
  const selected = new Set(collectionIds);
  let total = 0;
  for (const niche of MOCK_NICHES) {
    for (const collection of niche.collections) {
      if (selected.has(collection.id)) total += collection.productCount;
    }
  }
  return total;
}

export function collectionNamesForIds(collectionIds: string[]): string[] {
  const selected = new Set(collectionIds);
  return MOCK_NICHES.flatMap((niche) =>
    niche.collections.filter((c) => selected.has(c.id)).map((c) => c.name)
  );
}

/* ------------------------------------------------------------------ *
 * Stage 3b — demand probe (mock of the Apify "seed term analysis" run)
 * ------------------------------------------------------------------ */

export type MarketOption = {
  code: string;
  country: string;
  language: string;
  label: string;
};

export const MARKETS: MarketOption[] = [
  { code: "us-en", country: "United States", language: "English", label: "United States · English" },
  { code: "gb-en", country: "United Kingdom", language: "English", label: "United Kingdom · English" },
  { code: "sa-ar", country: "Saudi Arabia", language: "Arabic", label: "Saudi Arabia · Arabic" },
  { code: "ae-en", country: "United Arab Emirates", language: "English", label: "UAE · English" },
  { code: "de-de", country: "Germany", language: "German", label: "Germany · German" },
];

export const DEFAULT_MARKET = "us-en";

export function marketLabel(code: string): string {
  return MARKETS.find((m) => m.code === code)?.label ?? code;
}

/**
 * Wallet pricing — Stage 3 bills USD from the customer's wallet, not platform credits.
 * $10 per 1,000 raw keywords covers extraction + intent + matching.
 */
export const USD_PER_1K_KEYWORDS = 10;

export function usdForRawKeywords(rawKeywords: number): number {
  return Math.round((rawKeywords / 1000) * USD_PER_1K_KEYWORDS * 100) / 100;
}

export function formatUsd(amount: number): string {
  return `$${amount.toLocaleString("en-US", {
    minimumFractionDigits: amount % 1 === 0 ? 0 : 2,
    maximumFractionDigits: 2,
  })}`;
}

export const PROBE_STALE_MS = 30 * 24 * 60 * 60 * 1000;
export const PROBE_MS = 5_000;

export type SeedProbe = {
  seedId: string;
  market: string;
  rawKeywords: number;
  searchVolume: number;
  sampleKeywords: string[];
  checkedAt: number;
  failed?: boolean;
};

/** Plan examples first, then a deterministic fallback so mocks stay stable. */
const PROBE_RAW_BY_SEED: Record<string, number> = {
  sunglasses: 2400,
  "sun glasses": 1100,
  shades: 3200,
  eyewear: 48000,
  glasses: 39000,
  "women’s sunglasses": 850,
  "sunglasses for women": 640,
  "ladies’ sunglasses": 410,
  "women’s eyewear": 5200,
  "women’s glasses": 7400,
  toys: 26000,
  toy: 9100,
  playthings: 720,
  "kids’ products": 18500,
  "children’s toys": 6300,
  "educational toys": 2900,
  "learning toys": 1400,
  "learning products for kids": 980,
  "educational play products": 460,
  "board games": 8800,
  "tabletop games": 1900,
  "table games": 3100,
  "board game": 2600,
};

/** Ambiguous seeds must visibly return off-topic keywords in the preview. */
const PROBE_NOISE_SAMPLES: Record<string, string[]> = {
  glasses: [
    "drinking glasses",
    "wine glasses set",
    "reading glasses",
    "glasses for men",
    "blue light glasses",
  ],
  "table games": [
    "table tennis",
    "pool table games",
    "casino table games",
    "table games for kids",
    "dining table games night",
  ],
  eyewear: [
    "eyewear brands",
    "safety eyewear",
    "eyewear for men",
    "designer eyewear",
    "sports eyewear",
  ],
  "kids’ products": [
    "kids products online",
    "kids furniture",
    "kids clothing",
    "kids skincare products",
    "kids room decor",
  ],
};

function hashString(value: string): number {
  let hash = 0;
  for (let i = 0; i < value.length; i += 1) {
    hash = (hash * 31 + value.charCodeAt(i)) % 100000;
  }
  return hash;
}

const MARKET_SCALE: Record<string, number> = {
  "us-en": 1,
  "gb-en": 0.42,
  "sa-ar": 0.18,
  "ae-en": 0.14,
  "de-de": 0.36,
};

function rawKeywordsFor(row: MockSeedRow, market: string): number {
  const key = row.broadSeedVariation.toLowerCase();
  const base =
    PROBE_RAW_BY_SEED[key] ??
    (row.scopeMatch === "Broader"
      ? 22000 + (hashString(key) % 18000)
      : row.scopeMatch === "Ambiguous"
        ? 12000 + (hashString(key) % 9000)
        : 600 + (hashString(key) % 2400));
  const scaled = base * (MARKET_SCALE[market] ?? 0.5);
  return Math.max(60, Math.round(scaled / 10) * 10);
}

function sampleKeywordsFor(row: MockSeedRow): string[] {
  const key = row.broadSeedVariation.toLowerCase();
  const noise = PROBE_NOISE_SAMPLES[key];
  if (noise) return noise;
  const seed = row.broadSeedVariation.toLowerCase();
  return [
    `best ${seed}`,
    `${seed} online`,
    `buy ${seed}`,
    `cheap ${seed}`,
    `${seed} sale`,
  ];
}

/** Deterministic stand-in for the Apify seed-term analysis actor. */
export function buildSeedProbe(row: MockSeedRow, market: string): SeedProbe {
  const rawKeywords = rawKeywordsFor(row, market);
  const volumeFactor =
    row.scopeMatch === "Exact" ? 3.4 : row.scopeMatch === "Close" ? 2.6 : 1.8;
  return {
    seedId: row.id,
    market,
    rawKeywords,
    searchVolume: Math.round((rawKeywords * volumeFactor) / 10) * 10,
    sampleKeywords: sampleKeywordsFor(row),
    checkedAt: Date.now(),
  };
}

export function isProbeStale(probe: SeedProbe, market: string): boolean {
  return probe.market !== market || Date.now() - probe.checkedAt > PROBE_STALE_MS;
}

export type SelectionEstimate = {
  rows: number;
  rawKeywords: number;
  uniqueKeywords: number;
  searchVolume: number;
  usd: number;
  usdIfNotDeduped: number;
};

/**
 * Variations inside one canonical family return heavily overlapping keyword
 * sets, so billing on the raw sum would charge the client twice. We keep the
 * largest seed in each family whole and discount its siblings.
 */
const FAMILY_OVERLAP_DISCOUNT = 0.35;

export function estimateSelection(
  rows: MockSeedRow[],
  probes: Record<string, SeedProbe>
): SelectionEstimate {
  const probed = rows.filter((row) => probes[row.id] && !probes[row.id].failed);
  const byFamily = new Map<string, MockSeedRow[]>();
  for (const row of probed) {
    const key = `${row.collectionId}::${row.canonicalNicheSeed}`;
    byFamily.set(key, [...(byFamily.get(key) ?? []), row]);
  }

  let rawKeywords = 0;
  let uniqueKeywords = 0;
  let searchVolume = 0;

  for (const family of byFamily.values()) {
    const sorted = [...family].sort(
      (a, b) => probes[b.id].rawKeywords - probes[a.id].rawKeywords
    );
    sorted.forEach((row, index) => {
      const probe = probes[row.id];
      rawKeywords += probe.rawKeywords;
      searchVolume += probe.searchVolume;
      uniqueKeywords +=
        index === 0
          ? probe.rawKeywords
          : Math.round(probe.rawKeywords * FAMILY_OVERLAP_DISCOUNT);
    });
  }

  const usd = usdForRawKeywords(uniqueKeywords);
  return {
    rows: probed.length,
    rawKeywords,
    uniqueKeywords,
    searchVolume,
    usd,
    usdIfNotDeduped: usdForRawKeywords(rawKeywords),
  };
}

/** Greedy "fit to budget": keep the cheapest seeds with the best volume/$ . */
export function seedIdsWithinBudget(
  rows: MockSeedRow[],
  probes: Record<string, SeedProbe>,
  usdBudget: number
): string[] {
  const scored = rows
    .filter((row) => probes[row.id] && !probes[row.id].failed)
    .map((row) => {
      const price = usdForRawKeywords(probes[row.id].rawKeywords);
      return {
        row,
        price,
        volumePerDollar:
          probes[row.id].searchVolume / Math.max(0.01, price),
      };
    })
    .sort((a, b) => b.volumePerDollar - a.volumePerDollar);

  const kept: string[] = [];
  let spent = 0;
  for (const item of scored) {
    if (spent + item.price > usdBudget) continue;
    kept.push(item.row.id);
    spent += item.price;
  }
  return kept;
}

/** Customer-added broad seed (they know regional wording we may miss). */
export function createManualSeedRow(
  term: string,
  reference: MockSeedRow
): MockSeedRow {
  return {
    id: `manual-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`,
    collectionId: reference.collectionId,
    broadSeedVariation: term,
    canonicalNicheSeed: reference.canonicalNicheSeed,
    selectedCollection: reference.selectedCollection,
    broadParentNiche: reference.broadParentNiche,
    productCount: reference.productCount,
    variationType: "Regional terminology",
    scopeMatch: "Close",
    manual: true,
  };
}

export const STAGE_META: Record<
  MarketResearchStage,
  { label: string; shortLabel: string; agentPrompt: string; agentDetail: string }
> = {
  1: {
    label: "Niche read",
    shortLabel: "Niches",
    agentPrompt: "I studied your connected store and drafted the niches it appears to sell.",
    agentDetail:
      "Ask me anything about this read — challenge a niche, ask for a re-scan, or clarify what the site really sells. Categories and product counts stay hidden for now.",
  },
  2: {
    label: "Catalog scope",
    shortLabel: "Collections",
    agentPrompt: "Which collections should we analyze as the source catalog?",
    agentDetail:
      "Built from your Stage 1 niche agreement. Pick collections to study — product counts help gauge scope, not the niche to dominate.",
  },
  3: {
    label: "Seed terms & demand",
    shortLabel: "Seed terms",
    agentPrompt: "I’ve prepared broad niche seed variations for the selected collections.",
    agentDetail:
      "Each row is a market wording we’ll validate later for demand. No styles, materials, brands, or long-tail niches here — those come after you pick a niche to go deep on.",
  },
};

export type NicheReading = {
  id: string;
  name: string;
  summary: string;
  /** Edited or added by the customer instead of a full re-read. */
  edited?: boolean;
};

/** Stage 1 only — plain-language niches. No collections / product counts on screen. */
export const STAGE1_NICHE_READINGS: NicheReading[] = [
  {
    id: "eyewear",
    name: "Eyewear",
    summary:
      "The store looks centered on eyewear — sunglasses and related optical products as a clear parent niche.",
  },
  {
    id: "toys",
    name: "Toys",
    summary:
      "A second broad niche around toys in general — play, learning, and activity products sharing the same parent space.",
  },
  {
    id: "watches",
    name: "Watches",
    summary:
      "Watches appear as another parent niche on the site, separate from eyewear and toys.",
  },
];

/** Spoken Stage 1 conclusion the agent posts after analysis (mock). */
export function stage1AgentConclusion(
  storeLabel: string,
  readings: NicheReading[] = STAGE1_NICHE_READINGS
): string {
  const bullets = readings.map((n) => `• ${n.name} — ${n.summary}`).join("\n");
  const opening =
    readings.length === 1
      ? `I finished reading ${storeLabel}. It reads as a single broad niche:`
      : `I finished reading ${storeLabel}. From what’s on the site, it doesn’t look like a single niche — I see ${readings.length} broad parent spaces:`;

  return `${opening}

${bullets}

I’m not recommending what to dominate yet — only what the website already looks like it sells. If something feels wrong, tell me and I’ll ask before re-reading the store.`;
}

/** Streaming lines while Stage 1 analysis runs (no categories / counts). */
export const STAGE1_ANALYSIS_BEATS: { at: number; text: string }[] = [
  {
    at: 0,
    text: "Starting a first read of your connected store. I don’t assume your niche yet — I’m only looking at what the website appears to sell.",
  },
  {
    at: 0.25,
    text: "I’m walking the public pages and navigation to sense parent themes… still no final niche call.",
  },
  {
    at: 0.5,
    text: "Patterns are emerging — more than one broad product world on this site, not a single line.",
  },
  {
    at: 0.75,
    text: "Almost done. I’ll summarize parent niches in plain language — without dumping categories or product counts yet.",
  },
];

/** Duration of Stage 1 mock analysis (agent-driven later). */
export const STAGE1_ANALYSIS_MS = 12_000;

/** Stage 2 prep after customer presses Next (builds on Stage 1 niches). */
export const STAGE2_PREP_MS = 7_000;

export const STAGE2_PREP_BEATS: { at: number; text: string }[] = [
  {
    at: 0,
    text: "Locking the Stage 1 niche read. Next I’ll open catalog scope — expanding those parent niches into the collections already on your store.",
  },
  {
    at: 0.35,
    text: "Working in the background: matching each parent niche to the collections and category pages that belong under it…",
  },
  {
    at: 0.7,
    text: "Almost ready — you’ll pick which collections to study as the source catalog. Product counts show here so you can judge scope, not to force a choice.",
  },
];

export function stage2AgentReady(): string {
  return `Catalog scope is ready on the right. Based on the niches we aligned in Stage 1, I’ve laid out the collections under each parent niche.

Select one collection, several, or a whole niche — this only chooses what we study next, not what you should dominate. When you’re happy with the selection, press Next to generate broad seed variations.`;
}

/** Stage 3 prep after customer confirms Stage 2 catalog scope. */
export const STAGE3_PREP_MS = 8_000;

export const STAGE3_PREP_BEATS: { at: number; text: string }[] = [
  {
    at: 0,
    text: "Catalog scope locked. I’m treating each selected collection as a commercial catalog group — name, product count, and parent niche only.",
  },
  {
    at: 0.3,
    text: "Defining a canonical niche seed for every selected collection, then drafting broad wording variations (synonyms, spellings, broader terms)…",
  },
  {
    at: 0.65,
    text: "Labeling Exact / Close / Broader / Ambiguous. I’m not adding styles, materials, brands, or long-tail sub-niches at this stage.",
  },
];

export function stage3AgentReady(collectionCount: number, rowCount: number): string {
  return `Broad seed variations are ready on the right — ${rowCount} rows from ${collectionCount} selected collection${collectionCount === 1 ? "" : "s"}.

Each row is one broad market wording for later demand checks. Narrow styles and long-tails stay out until you pick a niche for deep research.`;
}

/** Agent narration while the demand probe runs (Stage 3b). */
export const PROBE_BEATS: { at: number; text: string }[] = [
  {
    at: 0,
    text: "Checking demand for the selected seeds — raw keyword count and search volume only, no full extraction yet.",
  },
  {
    at: 0.5,
    text: "Pulling counts per term and a sample of what each seed actually returns, so you can spot noisy wording before we spend anything.",
  },
];

export function probeAgentReady(
  seedCount: number,
  estimate: SelectionEstimate,
  market: string
): string {
  return `Demand check done for ${seedCount} seed${seedCount === 1 ? "" : "s"} in ${marketLabel(market)}.

Raw keywords across those terms: ${estimate.rawKeywords.toLocaleString("en-US")}. After removing the overlap between variations of the same canonical seed, you'd actually pay on about ${estimate.uniqueKeywords.toLocaleString("en-US")} — ${formatUsd(estimate.usd)} from your wallet.

Open a row to see sample keywords. If a broad term looks like noise, drop it here — that's the whole point of this stage.`;
}

export function createInitialProjects(): MarketResearchProject[] {
  // Empty first visit — customer names the first project, then boots Stage 1.
  return [];
}

export function formatProductCount(n: number): string {
  return n.toLocaleString("en-US");
}
