import type {
  MarketResearchProject,
  MarketResearchStage,
  MockNiche,
  MockSeedRow,
  NicheReading,
  SeedProbe,
} from "./mock-data";
import type { Stage1ChatMessage } from "./agent-panel";
import {
  normalizeOnPageInstructions,
  type CollectionContent,
  type ExtractedKeyword,
  type GeneratedArticle,
  type MarketResearchProduct,
  type OnPageInstructions,
  type ProposedCollection,
  type StrategyArticle,
  type WorkspaceTab,
} from "./workspace-data";

export type MarketResearchPersisted = {
  projects: MarketResearchProject[];
  activeProjectId: string;
  stage1DoneIds: string[];
  /** Highest stage the customer has opened via Next (per project). */
  openedMaxByProject: Record<string, MarketResearchStage>;
  /** Last viewed stage per project. */
  stageByProject: Record<string, MarketResearchStage>;
  chatByProject: Record<string, Stage1ChatMessage[]>;
  /** Collection ids Stage 3 was generated from (snapshot, per project). */
  stage3ScopeByProject: Record<string, string[]>;
  /** Seed rows the customer picked for the next stage (per project). */
  seedSelectionByProject: Record<string, string[]>;
  /** Stage 1 niches after customer edits. */
  nichesByProject: Record<string, NicheReading[]>;
  /** Stage 1 structured niches with collections discovered by agent. */
  structuredNichesByProject: Record<string, MockNiche[]>;
  /** Stage 2 full rich products for selected collections. */
  productsByProject: Record<string, MarketResearchProduct[]>;
  /** Stage 3 seed rows generated by agent. */
  seedRowsByProject: Record<string, MockSeedRow[]>;
  /** Target country + language the demand probe ran in. */
  marketByProject: Record<string, string>;
  /** Demand probe results keyed by seed row id. */
  probesByProject: Record<string, Record<string, SeedProbe>>;
  /** Broad seeds the customer added by hand. */
  manualSeedsByProject: Record<string, MockSeedRow[]>;
  /** Projects where Extract was paid and the workspace opened. */
  committedProjectIds: string[];
  workspaceTabByProject: Record<string, WorkspaceTab>;
  openedWorkspaceByProject: Record<string, WorkspaceTab>;
  clusterSelectionByProject: Record<string, string[]>;
  proposedCollectionsByProject: Record<string, ProposedCollection[]>;
  contentByIdByProject: Record<string, Record<string, CollectionContent>>;
  paidCollectionProjectIds: string[];
  contentReadyIds: string[];
  pushedIds: string[];
  customInstructionByProject: Record<string, OnPageInstructions>;
  /** Extract-stage intent split finished (sheets live inside stage 4). */
  analyzedProjectIds: string[];
  strategyReadyIds: string[];
  strategyApprovedIds: string[];
  extractChargeByProject: Record<string, number>;
  extractRowsByProject: Record<string, number>;
  keywordsByProject: Record<string, ExtractedKeyword[]>;
  /** Stage 7 article plan rows. */
  strategyByProject: Record<string, StrategyArticle[]>;
  /** Stage 7 generated article bodies keyed by article id. */
  articlesByProject: Record<string, Record<string, GeneratedArticle>>;
};

function storageKey(workspaceSlug: string) {
  return `market-research:v2:${workspaceSlug}`;
}

function migratedKey(workspaceSlug: string) {
  return `market-research:migrated:v1:${workspaceSlug}`;
}

export function emptyMarketResearchState(): MarketResearchPersisted {
  return {
    projects: [],
    activeProjectId: "",
    stage1DoneIds: [],
    openedMaxByProject: {},
    stageByProject: {},
    chatByProject: {},
    stage3ScopeByProject: {},
    seedSelectionByProject: {},
    nichesByProject: {},
    structuredNichesByProject: {},
    productsByProject: {},
    seedRowsByProject: {},
    marketByProject: {},
    probesByProject: {},
    manualSeedsByProject: {},
    committedProjectIds: [],
    workspaceTabByProject: {},
    openedWorkspaceByProject: {},
    clusterSelectionByProject: {},
    proposedCollectionsByProject: {},
    contentByIdByProject: {},
    paidCollectionProjectIds: [],
    contentReadyIds: [],
    pushedIds: [],
    customInstructionByProject: {},
    analyzedProjectIds: [],
    strategyReadyIds: [],
    strategyApprovedIds: [],
    extractChargeByProject: {},
    extractRowsByProject: {},
    keywordsByProject: {},
    strategyByProject: {},
    articlesByProject: {},
  };
}

export function markMarketResearchMigrated(workspaceSlug: string) {
  if (typeof window === "undefined") return;
  try {
    window.localStorage.setItem(migratedKey(workspaceSlug), "1");
  } catch {
    // ignore
  }
}

export function isMarketResearchMigrated(workspaceSlug: string): boolean {
  if (typeof window === "undefined") return false;
  try {
    return window.localStorage.getItem(migratedKey(workspaceSlug)) === "1";
  } catch {
    return false;
  }
}

function asStage(n: unknown): MarketResearchStage | null {
  const num = typeof n === "number" ? n : Number(n);
  if (num >= 1 && num <= 7) return num as MarketResearchStage;
  return null;
}

export function loadMarketResearchState(
  workspaceSlug: string
): MarketResearchPersisted | null {
  if (typeof window === "undefined") return null;
  try {
    const raw = window.localStorage.getItem(storageKey(workspaceSlug));
    if (!raw) {
      // Migrate lightly from v1 if present
      const v1 = window.localStorage.getItem(
        `market-research:v1:${workspaceSlug}`
      );
      if (!v1) return null;
      const parsed = JSON.parse(v1) as {
        projects?: MarketResearchProject[];
        activeProjectId?: string;
        stage1DoneIds?: string[];
      };
      if (!Array.isArray(parsed.projects)) return null;
      return {
        projects: parsed.projects,
        activeProjectId: parsed.activeProjectId ?? "",
        stage1DoneIds: Array.isArray(parsed.stage1DoneIds)
          ? parsed.stage1DoneIds
          : [],
        openedMaxByProject: {},
        stageByProject: {},
        chatByProject: {},
        stage3ScopeByProject: {},
        seedSelectionByProject: {},
        nichesByProject: {},
        structuredNichesByProject: {},
        productsByProject: {},
        seedRowsByProject: {},
        marketByProject: {},
        probesByProject: {},
        manualSeedsByProject: {},
        committedProjectIds: [],
        workspaceTabByProject: {},
        openedWorkspaceByProject: {},
        clusterSelectionByProject: {},
        proposedCollectionsByProject: {},
        contentByIdByProject: {},
        paidCollectionProjectIds: [],
        contentReadyIds: [],
        pushedIds: [],
        customInstructionByProject: {},
        analyzedProjectIds: [],
        strategyReadyIds: [],
        strategyApprovedIds: [],
        extractChargeByProject: {},
        extractRowsByProject: {},
        keywordsByProject: {},
        strategyByProject: {},
        articlesByProject: {},
      };
    }
    const parsed = JSON.parse(raw) as MarketResearchPersisted;
    if (!Array.isArray(parsed.projects)) return null;
    return {
      projects: parsed.projects,
      activeProjectId: parsed.activeProjectId ?? "",
      stage1DoneIds: Array.isArray(parsed.stage1DoneIds)
        ? parsed.stage1DoneIds
        : [],
      openedMaxByProject: parsed.openedMaxByProject ?? {},
      stageByProject: parsed.stageByProject ?? {},
      chatByProject: parsed.chatByProject ?? {},
      stage3ScopeByProject: parsed.stage3ScopeByProject ?? {},
      seedSelectionByProject: parsed.seedSelectionByProject ?? {},
      nichesByProject: parsed.nichesByProject ?? {},
      structuredNichesByProject: parsed.structuredNichesByProject ?? {},
      productsByProject: parsed.productsByProject ?? {},
      seedRowsByProject: parsed.seedRowsByProject ?? {},
      marketByProject: parsed.marketByProject ?? {},
      probesByProject: parsed.probesByProject ?? {},
      manualSeedsByProject: parsed.manualSeedsByProject ?? {},
      committedProjectIds: Array.isArray(parsed.committedProjectIds)
        ? parsed.committedProjectIds
        : [],
      workspaceTabByProject: parsed.workspaceTabByProject ?? {},
      openedWorkspaceByProject: parsed.openedWorkspaceByProject ?? {},
      clusterSelectionByProject: parsed.clusterSelectionByProject ?? {},
      proposedCollectionsByProject: parsed.proposedCollectionsByProject ?? {},
      contentByIdByProject: parsed.contentByIdByProject ?? {},
      paidCollectionProjectIds: Array.isArray(parsed.paidCollectionProjectIds)
        ? parsed.paidCollectionProjectIds
        : [],
      contentReadyIds: Array.isArray(parsed.contentReadyIds)
        ? parsed.contentReadyIds
        : [],
      pushedIds: Array.isArray(parsed.pushedIds) ? parsed.pushedIds : [],
      customInstructionByProject: migrateInstructionMap(
        parsed.customInstructionByProject
      ),
      analyzedProjectIds: Array.from(
        new Set([
          ...(Array.isArray(parsed.analyzedProjectIds)
            ? parsed.analyzedProjectIds
            : []),
          ...Object.entries(parsed.openedWorkspaceByProject ?? {})
            .filter(([, tab]) =>
              tab === "collections" ||
              tab === "content" ||
              (tab as string) === "analyze"
            )
            .map(([id]) => id),
        ])
      ),
      strategyReadyIds: Array.isArray(parsed.strategyReadyIds)
        ? parsed.strategyReadyIds
        : [],
      strategyApprovedIds: Array.isArray(parsed.strategyApprovedIds)
        ? parsed.strategyApprovedIds
        : [],
      extractChargeByProject: isNumberMap(parsed.extractChargeByProject),
      extractRowsByProject: isNumberMap(parsed.extractRowsByProject),
      keywordsByProject: isKeywordMap(parsed.keywordsByProject),
      strategyByProject: isArrayMap<StrategyArticle>(parsed.strategyByProject),
      articlesByProject: isObjectMap<GeneratedArticle>(parsed.articlesByProject),
    };
  } catch {
    return null;
  }
}

export function saveMarketResearchState(
  workspaceSlug: string,
  state: MarketResearchPersisted
) {
  if (typeof window === "undefined") return;
  try {
    window.localStorage.setItem(storageKey(workspaceSlug), JSON.stringify(state));
  } catch {
    // ignore quota / private mode
  }
}

export function clampOpenedStage(
  value: unknown,
  fallback: MarketResearchStage = 1
): MarketResearchStage {
  return asStage(value) ?? fallback;
}

function migrateInstructionMap(
  raw: unknown
): Record<string, OnPageInstructions> {
  if (!raw || typeof raw !== "object") return {};
  const out: Record<string, OnPageInstructions> = {};
  for (const [id, value] of Object.entries(raw as Record<string, unknown>)) {
    out[id] = normalizeOnPageInstructions(value);
  }
  return out;
}

function isNumberMap(raw: unknown): Record<string, number> {
  if (!raw || typeof raw !== "object") return {};
  const out: Record<string, number> = {};
  for (const [id, value] of Object.entries(raw as Record<string, unknown>)) {
    if (typeof value === "number" && Number.isFinite(value)) out[id] = value;
  }
  return out;
}

function isKeywordMap(raw: unknown): Record<string, ExtractedKeyword[]> {
  return isArrayMap<ExtractedKeyword>(raw);
}

function isArrayMap<T>(raw: unknown): Record<string, T[]> {
  if (!raw || typeof raw !== "object") return {};
  const out: Record<string, T[]> = {};
  for (const [id, value] of Object.entries(raw as Record<string, unknown>)) {
    if (Array.isArray(value)) out[id] = value as T[];
  }
  return out;
}

function isObjectMap<T>(raw: unknown): Record<string, Record<string, T>> {
  if (!raw || typeof raw !== "object") return {};
  const out: Record<string, Record<string, T>> = {};
  for (const [id, value] of Object.entries(raw as Record<string, unknown>)) {
    if (value && typeof value === "object" && !Array.isArray(value)) {
      out[id] = value as Record<string, T>;
    }
  }
  return out;
}

