export {
  AUTOMMERCE_COLORS,
  AUTOMMERCE_GRADIENTS,
  AUTOMMERCE_LOGOS,
  AUTOMMERCE_TYPOGRAPHY,
  PRODUCT_NAME,
  PRODUCT_FULL_NAME,
  PRODUCT_TAGLINE,
  PRODUCT_ORIGIN,
  CRAWLER_USER_AGENT,
} from "./tokens";

